In [ ]:
"""Importing all necessary modules"""
import pandas as pd

In [ ]:
"""Downloading the required dataset"""
from google.colab import drive
drive.mount('/content/gdrive')

import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive

#changing the working directory
%cd /content/gdrive/My Drive/Kaggle#Check the present working directory using pwd command

!kaggle datasets download -d ruthgn/wine-quality-data-set-red-white-wine

#unzipping the zip files and deleting the zip files
!unzip \*.zip  && rm *.zip

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
[Errno 2] No such file or directory: '/content/gdrive/My Drive/Kaggle#Check the present working directory using pwd command'
/content
Downloading wine-quality-data-set-red-white-wine.zip to /content
  0% 0.00/98.0k [00:00<?, ?B/s]
100% 98.0k/98.0k [00:00<00:00, 54.0MB/s]
Archive:  wine-quality-data-set-red-white-wine.zip
replace wine-quality-white-and-red.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
"""Reading the dataset"""
ds_train=pd.read_csv("/content/wine-quality-white-and-red.csv")

In [ ]:
"""change the categorical feature type into numerical(we dont use it but there was an error for calculating median,mean etc, so I changed it to not have the annoying error."""
ds_train["type"] = ds_train["type"].map({"white" : 0, "red" : 1})

In [ ]:
"""Here we can see the mean value, standard deviation, as well as other important informaation such as min and max values which represent the range of values for each collumn"""
ds_train.describe()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,0.246114,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,0.430779,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,0.000000,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,0.000000,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,0.000000,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,0.000000,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,1.000000,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [ ]:
"""We can see the mode"""
ds_train.mode()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.0,6.8,0.28,0.3,2.0,0.044,29.0,111.0,0.9972,3.16,0.5,9.5,6.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9976,NaN,NaN,NaN,NaN

In [ ]:
"""Such is the median"""
ds_train.median()

type                      0.00000
fixed acidity             7.00000
volatile acidity          0.29000
citric acid               0.31000
residual sugar            3.00000
chlorides                 0.04700
free sulfur dioxide      29.00000
total sulfur dioxide    118.00000
density                   0.99489
pH                        3.21000
sulphates                 0.51000
alcohol                  10.30000
quality                   6.00000
dtype: float64

In [ ]:
"""The variance"""
ds_train.var()

type                       0.185570
fixed acidity              1.680740
volatile acidity           0.027105
citric acid                0.021117
residual sugar            22.636696
chlorides                  0.001227
free sulfur dioxide      315.041192
total sulfur dioxide    3194.720039
density                    0.000009
pH                         0.025853
sulphates                  0.022143
alcohol                    1.422561
quality                    0.762575
dtype: float64

In [ ]:
"""And this is the correlation to the target"""
true_cor=ds_train.corr()["quality"]
corr=abs(ds_train.corr()["quality"]).sort_values(ascending=False)
corr.update(true_cor)
corr.drop(["quality"])

alcohol                 0.444319
density                -0.305858
volatile acidity       -0.265699
chlorides              -0.200666
type                   -0.119323
citric acid             0.085532
fixed acidity          -0.076743
free sulfur dioxide     0.055463
total sulfur dioxide   -0.041385
sulphates               0.038485
residual sugar         -0.036980
pH                      0.019506
Name: quality, dtype: float64

I think thaat the correlation between the quality and the alcohol inside it makes a lot of sense, as a wine with little alcohol is rather grape juice, and would be considered as a subpar drink. the volatile acidity and density being the 2 quality runnerups, also make sense, as many consider the more thick wine to have a better taste, thus quality and being slightly acid is always welcomed, as such is the nature of alcohol. The others all have a bigger/smaller impact on the target, but none as much as there 3.